name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build shadowJar --no-daemon
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Find JAR file
        id: find_jar
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -n 1)
          echo "JAR_PATH=$JAR_FILE" >> $GITHUB_OUTPUT
          echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_jar.outputs.JAR_PATH }}
          generate_release_notes: true
          draft: false
          prerelease: false
          name: WorldLink ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## WorldLink v${{ steps.get_version.outputs.VERSION }}
            
            ### 📦 Installation
            Download the JAR file below and place it in your server's `plugins/` folder.
            
            ### ✨ Requirements
            - Minecraft: 1.21+
            - Server: Paper/Spigot
            - Java: 21+
            
            ### 📝 Changelog
            See the automatically generated release notes below for details on what's changed.
